application: gv-commander
version: 1
runtime: python27
api_version: 1
threadsafe: false

inbound_services:
- xmpp_message
- mail

handlers:
- url: /_ah/mail/.+
  script: main.py
- url: /_ah/xmpp/message/chat/.*
  script: main.py
